### ISSUE TITLE
The API is not gather information

### ISSUE THREAD

**Issue by Dennis-LCLema** [Dennis-LCLema/GroupProject#11]
The API we are using is not connecting properly to our app. 

- 

- [x] Might need to use a different API or figure out the bug.

- [x] Develop a new code that will allow us to gather information

- [x] These are just some test

**Comment by MattRubbelke** [comment]
Which API is this?

**Comment by MattRubbelke** [comment]
Maybe use https://platform.seatgeek.com/

**Comment by LianaSun** [comment]
This issue has been solved and closed
